name: "Foundry Build"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: contracts/bridge
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Fuzz
        run: make fuzz
      - run: which fuzz

      - name: test
        run: forge test
