name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            os_attr: linux
          - os: macos-latest
            os_attr: darwin
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: contracts/bridge
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          # https://discourse.nixos.org/t/understanding-binutils-darwin-wrapper-nix-support-bad-substitution/11475/2
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: dapp
      - name: build
        run: nix-shell --pure --command 'make build'
      - name: test
        run: nix-shell --pure --command 'make test'
      - name: smt-checker
        run: nix-shell --pure --command 'make smt-checker'
